sudo: required
services:
  - docker
before_install:
  - docker build -t pankajsherchan/network-overflow-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true pankajsherchan/network-overflow-test npm test -- --coverage
after_success:
  - docker build -t pankajsherchan/network-overflow-client ./client
  - docker build -t pankajsherchan/network-overflow-nginx ./nginx
  - docker build -t pankajsherchan/network-overflow-server ./server

  # push the docker image to the docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push pankajsherchan/network-overflow-client
  - docker push pankajsherchan/network-overflow-nginx
  - docker push pankajsherchan/network-overflow-server
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-122917187984
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
