version: "3"
services:
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      # - /app/node_modules
      - app-nodemodules:/app/node_modules # ! Map to local node_modules volume local development
      - ./client:/app
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - api
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      # - app-server-nodemodules:/app/node_modules # ! Map to local node_modules volume local development
      - ./server:/app
  #   links:
  #     - mongo
  # mongo:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - "27017:27017"
  # volumes:
  #   - ./server/data:/data/db
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
volumes:
  app-nodemodules:
    external: true
  # app-server-nodemodules:
  #   external: true
